### ISSUE TITLE
Fatal Internal CLR Error Getting Authenticode Info

### ISSUE THREAD

**Issue by gfs** [secana/PeNet#141]
```
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UInt64)
   at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
   at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
   at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)
```

[This](https://github.com/microsoft/AttackSurfaceAnalyzer/blob/4490a0213830a3dcbff5d124b682afedf9d65e08/Lib/Collectors/WindowsFileSystemUtils.cs#L32) is the line in `GetSignatureStatus`.

[Microsoft.Management.Infrastructure.Native.dll.zip](https://github.com/secana/PeNet/files/4585089/Microsoft.Management.Infrastructure.Native.dll.zip) is a example of a file that causes the crash.  It is a 32 bit arm binary (native dependency).

PeNet Version: 2.2.1
DotNet Version: 3.1.201

**Comment by secana** [comment]
ARM binaries seem to be a problem as I never tested them with PeNet. I fixed the issue above and hope to catch all ARM binaries with it. If you find any more samples that do not work correctly let me know. I want the library to be as complete as possible. New version 2.2.2 should be on NuGet in a few minutes.

**Comment by gfs** [comment]
Thanks for the quick response! Will definitely let you know if I run into any interesting binaries.
