### ISSUE TITLE
Fatal Internal CLR Error Getting Authenticode from Attached

### ISSUE THREAD

**Issue by gfs** [secana/PeNet#142]
This one is a dependency in a linux build of one of my tools.  It passes the `PeFile.IsPeFile(Path)` check. [Microsoft.VisualBasic.Core.dll.zip](https://github.com/secana/PeNet/files/4587936/Microsoft.VisualBasic.Core.dll.zip)

```
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer.__Memmove(Byte*, Byte*, UInt64)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UInt64)
   at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
   at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
   at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)
```

[This](https://github.com/microsoft/AttackSurfaceAnalyzer/blob/4490a0213830a3dcbff5d124b682afedf9d65e08/Lib/Collectors/WindowsFileSystemUtils.cs#L32) is the line in `GetSignatureStatus`.

**Comment by secana** [comment]
That's a real interesting one! It has the machine type of "0xfd1d" which is undocumented by Microsoft (https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#machine-types) and I've never seen it before. I've added the unknown architecture as a x64 bit one and the file parses now correctly. As soon as the build pipelines ran through, a new version should be available.

**Comment by secana** [comment]
2.2.4 is on Nuget. Let's see what you find next :)
