### ISSUE TITLE
Fatal Internal CLR Error

### ISSUE THREAD

**Issue by gfs** [secana/PeNet#143]
```
Fatal error. Internal CLR error. (0x80131506)
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Buffer.Memmove(Byte ByRef, Byte ByRef, UInt64)
   at System.Span`1[[System.Byte, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
   at PeNet.Header.Authenticode.ContentInfo..ctor(System.Span`1<Byte>)
   at PeNet.Header.Authenticode.AuthenticodeInfo..ctor(PeNet.PeFile)
   at PeNet.HeaderParser.Authenticode.AuthenticodeParser.ParseTarget()
   at PeNet.PeFile.get_Authenticode()
   at AttackSurfaceAnalyzer.Collectors.WindowsFileSystemUtils.GetSignatureStatus(System.String)
```

I found the file at `C:\Users\Gstoc\.nuget\packages\microsoft.netcore.app.runtime.osx-x64\3.1.3\runtimes\osx-x64\lib\netcoreapp3.1\Microsoft.VisualBasic.Core.dll`.

[Microsoft.VisualBasic.Core.dll.zip](https://github.com/secana/PeNet/files/4589793/Microsoft.VisualBasic.Core.dll.zip)

**Comment by secana** [comment]
Again an undocumented machine type 0xC020. I gave feedback on the MS documentation to add the missing types. Version 2.2.5 with a fix is on it's way to nuget.org.

**Comment by secana** [comment]
found another one. version 2.2.5 should hopefully cover all cases.

**Comment by gfs** [comment]
> I gave feedback on the MS documentation to add the missing types. 
Where did you give feedback?  You can submit a PR to update the file by editing the .MD file here: https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/Debug/pe-format.md.

**Comment by secana** [comment]
Hi gfs, submitted feedback over the "do you like this page" as they is no comment section.

I would like to make PR but the I know only the value but not the correct name of the constant. If you are able to find that out, that would be great. The values are:

- 0xC020
- 0xfd1d

**Comment by gfs** [comment]
Got it. I will try to see if I can find the right folks internally.

-------- Original Message --------
