### ISSUE TITLE
NullReferenceException in Find

### ISSUE THREAD

**Issue by cwchapma** [secana/PeNet#2]
I'm getting a null NullReferenceException.  Somehow t.Fail is null.

```
   at PeNet.PatternMatching.Trie2.<Find>d__3.MoveNext() in D:\Users\Clint\Documents\Visual Studio 2015\Projects\ConsoleApplication1\PeNet2\PatternMatching\AhoCorasick.cs:line 163
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at ConsoleApplication1.Program.Main(String[] args) in d:\users\clint\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 26
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This is my program:

    class Program
    {
        static void Main(string[] args)
        {
            var pe = new PeFile(@"c:\windows\system32\calc.exe");

            var trie = new Trie();

            var nsisSig = StringToByteArray("83 EC 20 53 55 56 33 DB 57 89 5C 24 18 C7 44 24 10");
            var s = BitConverter.ToString(nsisSig);

            trie.Add(nsisSig, "NSIS");

            var matches = trie.Find(pe.Buff);

            var count = matches.Count();

            foreach (var match in matches)
            {
                Console.WriteLine($"Pattern {match.Item1} at offset {match.Item2}");
            }
        }

        public static byte[] StringToByteArray(string hex)
        {
            hex = hex.Replace(" ", "");
            return Enumerable.Range(0, hex.Length)
                             .Where(x => x % 2 == 0)
                             .Select(x => Convert.ToByte(hex.Substring(x, 2), 16))
                             .ToArray();
        }
    }

**Comment by cwchapma** [comment]
I see now, I forgot to call trie.Build();

**Comment by secana** [comment]
Hi cwchapma, I think it's a good idea to make the "Build" command build in the Find. It's more intuitive. I'll update the code a soon as possible. Thx for your feedback :)
